# Values used for the deployed application.
replicaCount: 1
service:
  name: upp-exports-rw-s3
env:
  bucket:
    name: "com.ft.universalpublishing.enrichedcontentdata"
    prefix: "k8s-unarchived"
    concept:
      prefix: "k8s-concept-unarchived"
    content:
      prefix: "k8s-content-unarchived"
  content:
    resource:
      path: "content"
  concept:
    resource:
      path: "concept"
  log:
    metrics: "false"
